spring:
  application:
    name: sport-nacos
  profiles:
    active: dev

server:
  port: 8000


cloud:
    # ========================nacos===================
    nacos:
      discovery:
        server-addr: localhost:8848
#消费者将要去访问的微服务名称(nacos微服务提供者叫什么你写什么)
service-url:
  nacos-user-service: http://nacos-payment-provider

logging:
  file:
    path: /logs/sport