spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/aioveu_oms?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: ${mysql.username}
    password: ${mysql.password}
  # RabbitMQ 配置
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual   
  data:
    redis:
      database: ${redis.database}
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      lettuce:
        pool:
          min-idle: 1
mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Seata 配置
seata: 
  # 开启 Seata
  enabled: true
  # 事务分组名称
  tx-service-group: default_tx_group
  service:
    # 事务分组映射，根据分组名称匹配到集群
    vgroup-mapping:
      # 事务分组名称：集群名称
      default_tx_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.server-addr}
      namespace:
      group: SEATA_GROUP  

# Feign 配置
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  sentinel:  # 开启feign对sentinel的支持
    enabled: false

# 安全配置
security:
  # 白名单路径
  whitelist-path:
      - /app-api/v1/carts

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aioveu.oms.controller
  # Api文档信息
  info:
    title: 订单服务
    version: 3.0.0
    description: 订单、购物车等接口
    contact:
      name: aioveu
      url: https://www.aioveu.com
      email: ambitiouschild@qq.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn


wx:
  pay:
    # 必需配置
    app-id: wx1234567890abcdef      # 你的微信小程序AppId
    mch-id: 1230000109               # 你的商户号
    mch-key: your-mch-key-32-chars   # API密钥，32位
    notify-url: https://your-domain.com/api/wxpay/notify

    # 可选配置
    sign-type: MD5                   # 签名类型：MD5 或 RSA
    sandbox-enabled: false           # 是否使用沙箱环境

    # 以下为可选证书配置（如果需要）
    # key-path: classpath:/cert/apiclient_cert.p12
    # private-key-path: classpath:/cert/apiclient_key.pem
    # private-cert-path: classpath:/cert/apiclient_cert.pem
    # api-v3-key: your-api-v3-key
    # cert-serial-no: your-cert-serial-no

    # 兼容字段
    # pay-notify-url: https://your-domain.com/api/wxpay/notify