redis:
  database: 0
  host: localhost
  port: 6379
  password: 775825
  
mysql:
  host: localhost
  port: 3306
  username: root
  password: 775825

rabbitmq:
  host: localhost
  port: 5672
  username: adminlss
  password: adminlss


# 验签公钥地址
spring:
  security:
    oauth2:
      authorizationserver:
        token-uri: ${gateway.endpoint}/aioveu-auth/oauth2/token
      resourceserver:
        jwt: 
          jwk-set-uri: ${gateway.endpoint}/aioveu-auth/oauth2/jwks

# 网关地址
gateway:
  endpoint: http://localhost:9999

# Nacos 配置中心地址(Seata RM、TM 注册)
nacos:
  server-addr: http://localhost:8848

# 短信配置
sms:
  # 阿里云短信
  aliyun:
    accessKeyId: LTAI5tSMgfxxxxxxdiBJLyR
    accessKeySecret: SoOWRqpjtS7xxxxxxZ2PZiMTJOVC
    domain: dysmsapi.aliyuncs.com 
    regionId: cn-shanghai
    signName: 可我不敌可爱
    templateCodes: 
      register: SMS_22xxx771
      login: SMS_22xxx770


