spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/aioveu_system?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: ${mysql.username}
    password: ${mysql.password}
  data:
    redis:
      database: ${redis.database}
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      lettuce:
        pool:
          min-idle: 1
  # RabbitMQ 配置
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true
  cloud:
    sentinel:
      enabled: false
      eager: true # 取消控制台懒加载，项目启动即连接Sentinel
      transport:
        client-ip: localhost
        dashboard: localhost:8080
      datasource:
        # 限流规则，flow为key，随便定义
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow
        # 降级规则
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: degrade

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  sentinel:  # 开启feign对sentinel的支持
    enabled: false



# 安全配置  YAML 缩进错误导致配置没有被正确加载。这个配置的必须顶头
# 安全配置
security:

  # 安全白名单路径，仅跳过 AuthorizationFilter 过滤器，还是会走 Spring Security 的其他过滤器(CSRF、CORS等)
  ignore-urls:
    # 登录接口(账号密码登录、手机验证码登录和微信登录)
    - /api/v1/auth/login/**
    # 验证码获取接口
    - /api/v1/auth/captcha
    # 刷新令牌接口
    - /api/v1/auth/refresh-token
    # 开放退出登录
    - /api/v1/auth/logout
    # WebSocket接口
    - /ws/**

  # 非安全端点路径，完全绕过 Spring Security 的安全控制
  unsecured-urls:
    - ${springdoc.swagger-ui.path}
    - /doc.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /webjars/**
    - /favicon.ico

#用户服务中的密码处理
password:
  encoder:
    type: bcrypt  # 可选: bcrypt, pbkdf2, scrypt, argon2, sha256, md5, delegating
  bcrypt:
    # BCrypt强度(4-31)，默认10
    strength: 10
  pbkdf2:
    iterations: 310000
    # 可选秘钥
    secret: "my-secret-key"
  argon2:
    saltLength: 16
    hashLength: 32
    parallelism: 1
    # 内存使用(KB)
    memory: 4096
    iterations: 3

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # ✅ 显示配置
    display-request-duration: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    # ✅ 文档扩展
    doc-expansion: none
    default-models-expand-depth: 2
    default-model-expand-depth: 2

  api-docs:
    path: /v3/api-docs
    enabled: true

    # ✅ 组配置修复
  group-configs:
    - group: 'default'
      display-name: '系统服务'
      # 关键：这里匹配控制器的实际路径
      paths-to-match:
        -'/api/v1/**'
      packages-to-scan:
        - com.aioveu.system.controller
        - com.aioveu.common.file.controller

  # Api文档信息
  info:
    title: 系统服务
    version: 3.0.0
    description: 用户、部门、角色、菜单、字典等接口
    contact:
      name: aioveu
      url: https://www.aioveu.com
      email: ambitiouschild@qq.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html

# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 是否开启 Knife4j 增强功能
  # 设置为 true 表示开启增强功能
  #蓝色：识别为YAML关键字（true/false/null等）
  #橙色/黄色：识别为字符串值
  #当值后面有空格时，某些编辑器会认为这是"不纯净"的值，可能按字符串处理
  enable: true
  # 生产环境配置
  # 设置为 true 表示在生产环境中不显示文档，为 false 表示显示文档（通常在开发环境中使用）
  production: false
  setting:
    # 基础配置-------------
    language: zh_cn
    enable-version: true
    # ✅ 开启重载功能
    enable-reload: true
    enable-open-api: true

    # 启用请求缓存
    enable-request-cache: true
    # 自动添加认证头
    enable-filter-multipart-apimethod: 4
    # Token 自动管理
    enable-after-script: true


    # 搜索和国际化-------------
    enable-search: true
    enable-i18n: true





# 文件存储
oss:
  # OSS 类型 (目前支持aliyun、minio) #aliyun
  type:  minio
  # MinIO 对象存储服务
  minio:
    # 服务Endpoint
    endpoint: http://localhost:9002
    # 访问凭据
    access-key: minioadminlss
    # 凭据密钥
    secret-key: minioadminlss
    # 存储桶名称
    bucket-name: default
    # (可选)自定义域名，如果配置了域名，生成的文件URL是域名格式，未配置则URL则是IP格式 (eg: https://oss.aioveu.tech)
    # custom-domain:
  # 阿里云OSS对象存储服务
  aliyun:
    # 服务Endpoint
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 访问凭据
    access-key-id: your-access-key-id
    # 凭据密钥
    access-key-secret: your-access-key-secret
    # 存储桶名称
    bucket-name: default

# system 的 Nacos 配置
management:
  health:
    mail:
      enabled: false  # 禁用邮件健康检查




# ========== 日志配置（便于调试） ==========
logging:
  level:
    com.aioveu: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.github.xiaoymin: DEBUG