<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.aioveu</groupId>
        <artifactId>aioveu-common</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>common-security-resource</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    </properties>

    <dependencies>

        <!-- ✅ 你的 core -->
<!--        <dependency>-->
<!--            <groupId>com.aioveu</groupId>-->
<!--            <artifactId>common-core</artifactId>-->
<!--            <version>${project.version}</version>-->
<!--        </dependency>-->

        <!-- ✅ 依赖 security-core -->
        <dependency>
            <groupId>com.aioveu</groupId>
            <artifactId>common-security-core</artifactId>
            <version>${project.version}</version>
        </dependency>



        <!-- ✅ 资源服务器自动配置 -->  <!-- ✅ 这个依赖自带 Jwt 已经包含 Jwt / JwtAuthenticationToken-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>


<!--        显式声明这个包-->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-jose</artifactId>
        </dependency>

        <!-- ✅ Web（必须） -->
        <dependency>
            <groupId>com.aioveu</groupId>
            <artifactId>common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.aioveu</groupId>
            <artifactId>common-feign</artifactId>
        </dependency>


        <dependency>
            <groupId>com.aioveu</groupId>
            <artifactId>tenant-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- 不引 starter -->
        <!-- 不引 mybatis-plus-core -->
        <!-- 不引 jsqlparser 单独 -->

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
        </dependency>

    </dependencies>



</project>