# 基础镜像 指定具体 Alpine 版本
FROM aioveu-17-jdk-slim

# 维护者信息

# 设置 UTF-8 编码环境 方案一：在 Dockerfile 中显式指定 UTF-8 环境（推荐）
ENV LANG=C.UTF-8 \
    TZ=Asia/Shanghai

LABEL maintainer="ambitiouschild@qq.com"
LABEL project="aioveu-tenant-oms"

# 版本 5.2.0：支持小程序上架
LABEL version="v5.2.0"

#方案一：如果您使用的是 Debian/Ubuntu 基础镜像
# 替换为 apt-get 命令
RUN apt-get update \
#    && apt-get install -y --no-install-recommends tzdata fonts-dejavu fontconfig \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# /tmp 目录作为容器数据卷目录，SpringBoot内嵌Tomcat容器默认使用/tmp作为工作目录，任何向 /tmp 中写入的信息不会记录进容器存储层
# 在宿主机的/var/lib/docker目录下创建一个临时文件并把它链接到容器中的/tmp目录
VOLUME /tmp

# 复制主机文件至镜像内，复制的目录需放置在 Dockerfile 文件同级目录下
ADD target/oms-boot.jar app.jar

# 容器启动执行命令
#CMD java \
#    -Xms512m \        # 初始堆512MB
#    -Xmx1536m \       # 最大堆1.5GB
#    -XX:MaxMetaspaceSize=256m \  # 元空间256MB
#    -XX:ReservedCodeCacheSize=128m \  # JIT缓存128MB
#    -XX:MaxDirectMemorySize=256m \    # 堆外内存256MB
#    -XX:+UseContainerSupport \    # 容器感知
#    -XX:+UseG1GC \                # G1垃圾回收器
#    -XX:MaxGCPauseMillis=200 \    # GC暂停目标200ms
#    -Djava.security.egd=file:/dev/./urandom \
#    -jar /app.jar

CMD java \
    -Xms512m \
    -Xmx1536m \
    -XX:MaxMetaspaceSize=256m \
    -XX:ReservedCodeCacheSize=128m \
    -XX:MaxDirectMemorySize=256m \
    -XX:+UseContainerSupport \
    -XX:+UseG1GC \
    -XX:MaxGCPauseMillis=200 \
    -Djava.security.egd=file:/dev/./urandom \
    -Djdk.internal.platform.disable=true  \
    -jar /app.jar

# 声明容器提供服务端口
EXPOSE 8803



